name: Daily Commit

on:
  schedule:
    - cron: '30 4 * * *'    # 10:00 AM IST
    - cron: '30 16 * * *'   # 10:00 PM IST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update File
        run: |
          echo "Commit: $(date)" >> activity.txt

      - name: Commit Changes
        run: |
          git config user.name "vineetbhardwaj001"
          git config user.email "bhardwajvineet990@gmail.com"

          git add .

          git commit -m "Daily auto commit" || exit 0

          git push
